# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "gh-flow-gh-flow-terraform-state"
    key    = "projects/gh-flow/kms/terraform.tfstate"
    region = "us-east-2"
  }
}
