# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.52.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region              = "us-east-2"
  allowed_account_ids = ["237918751012"]
}

