# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "me-gh-flow-terraform-state"
    key     = "projects/gh-flow/containers/terraform.tfstate"
    profile = "gh-flow"
    region  = "us-east-2"
  }
}
